### PR TITLE
Configurable JsonPath for pod owner

### PR DESCRIPTION
**Pull request by IlyaMar**
This is a fix for https://github.com/jgroups-extras/jgroups-kubernetes/issues/50
New property 'podOwnerJsonPath' added with JsonPath to pod owner (ReplicaSet or OpenShift Deployment) relative to pod json node. Default value is "$.metadata.labels.deployment" to keep backward compatibility.
For kubernetes w/o OpenShift, property value should be set to "$.metadata.ownerReferences[?(@['kind'] == 'ReplicaSet')].name"

Please note new dependency is added, com.jayway.jsonpath:json-path. It should be placed to JBoss module somehow, by adding a new jar or by a shaded jar, please advice how to do it.

### CODE REVIEW

**Comment by IlyaMar** [comment]
Autodetection sounds reasonable and easy to implement. I have a question about StatefulSets, it's not clear by what criteria should we distinguish new and old pods during rolling update. 
It looks like we can segregate pods by "controller-revision-hash" label but I see no documentation on it.
Please see json attached, it is taken in the middle of rolling update
[pods_upd1.zip](https://github.com/jgroups-extras/jgroups-kubernetes/files/3373822/pods_upd1.zip)

**Comment by slaskawi** [comment]
> I have a question about StatefulSets, it's not clear by what criteria should we distinguish new and old pods during rolling update. It looks like we can segregate pods by "controller-revision-hash" label but I see no documentation on it. 

@IlyaMar Indeed, `controller-revision-hash` seems to be very poorly documented. However, [this issue](https://github.com/kubernetes/kubernetes/issues/47554) suggests the change has been done on purpose and will be permanent. I guess we could use this field (however, I guess it would be wise to prepare for a null reference there and print out some warning in such a case).

**Comment by IlyaMar** [comment]
@slaskawi I've updated PR with controller-revision-hash usage, please review.

**Comment by IlyaMar** [comment]
I've found a new problem just now. When performing Rolling Update, new pod is not fully started at the moment KUBE_PING performs discovery. So, new pod is filtered out in org.jgroups.protocols.kubernetes.Client#parseJsonResult
As result, we cannot determine senderParentDeployment variable inside org.jgroups.protocols.kubernetes.KUBE_PING#findMembers, and old members are not filtered from cluster list. New pod cannot start as it stuck communicating with old members.
[pods_upd2.zip](https://github.com/jgroups-extras/jgroups-kubernetes/files/3396680/pods_upd2.zip)

I think we need to move filtraton by readiness to findMembers function, after senderParentDeployment is determined.

**Comment by slaskawi** [comment]
> When performing Rolling Update, new pod is not fully started at the moment KUBE_PING performs discovery. So, new pod is filtered out in org.jgroups.protocols.kubernetes.Client#parseJsonResult
As result, we cannot determine senderParentDeployment variable inside org.jgroups.protocols.kubernetes.KUBE_PING#findMembers, and old members are not filtered from cluster list. New pod cannot start as it stuck communicating with old members.

@IlyaMar So indeed, `Client#parseJsonResult` checks if Pod is running (that in turn invokes `Client#podRunning`, which checks both flags - is `Running` and is `ready`). Then, we exclude all Pods that do not pass this predicate from the `List<Pod>` returned by `Client#parseJsonResult`.

Then, as you said, the Pods that are not ready (or are not running) are not processed by in `KUBE_PING#findMembers`. But since, they are not there, they shouldn't form a cluster. In other words, not ready Pods should not join any cluster (neither `old`, nor `new` one). 

However, as you said, the Pod that is sending the discovery request also might not be ready. Since it's not present in a list returned by `Client#parseJsonResult` it can not grab it's own Parent Deployment (stored in `senderParentDeployment`), and it can not compare it to the other Pods and we get into troubles.

I believe we have at least 3 choices here:

1. if `senderParentDeployment` is null, we simply exclude all Pods from the discovery. This means the Pod that is sending the discovery request is not ready, so it doesn't know which cluster to join. The biggest downside is that an application may be in not-ready state for a longer period of time (e.g. doing a migration or fetching a larger dataset from a database). So clearly, this solution is not perfect.
2. We can modify the `Client#getPods` to always preserve a sender Pod. Later on, we can filter the sender in `KUBE_PING#findMembers`. However, sending discovery to `self` should not do any harm.
3. As you mentioned, move the whole `if (split_clusters_during_rolling_update)` to the `Client#parseJsonResult` and adjust the readiness check part.

I personally like the option no. 3 the most. I think that's the cleanest approach. no. 2 is also "pretty good".

**Comment by IlyaMar** [comment]
Ok, I'll implement option #3. Change will be included in the same pull
request.

ср, 17 июля 2019 г., 11:57 Sebastian Łaskawiec <notifications@github.com>:

**Comment by IlyaMar** [comment]
@slaskawi , I finally implemented slightly different solution. Client now reads all pods, even not ready, with flag isReady. It's KUBE_PING.findMembers responsibility to form a list of members from this pod list. Looks like this resulted to more readable code. Please see updated PR.

**Comment by belaban** [comment]
Hey @slaskawi thanks for looking into this! Can you merge the PR, or do you need further testing?

**Comment by slaskawi** [comment]
@belaban No, I believe it's fine! I just wanted to check if you have any comments regarding to the code.

**Comment by belaban** [comment]
done

**Comment by belaban** [comment]
@slaskawi I appreciate that you can still find time to spend on Kubernetes/Openshift discovery protocols (KUBE_PING, DNS_PING)!
The beers are on me during the Barcelona F2F! :-)
Thanks!!

**Pull request merged**
