### PR TITLE
kubernetes.KUBE_PING - dont repeat warn message when kubernetes endpo…

### PR DESCRIPTION
**Pull request by TomasHofman**
…int unavailable

https://issues.redhat.com/browse/JBEAP-20779

### CODE REVIEW

**Comment by TomasHofman** [comment]
Hello @belaban , would this change be all right?

Also, is there a 1.0.x branch somewhere? The issue was reported for EAP 7.3.x, which uses jgroups-kubernetes 1.0.13 currently.

**Comment by belaban** [comment]
Hi @TomasHofman 
sure, applied.
Yes, there is a "1.x" branch, which uses the 4.x version of JGroups. You'd have to submit another PR against that branch if you want to release a jgroups-kubernetes 1.0.16. If you do that, I could release 1.0.16 right away...
Cheers,

**Comment by TomasHofman** [comment]
@belaban Thanks.

I can't see the 1.x branch in this repo either. Only see master and stable.

**Comment by belaban** [comment]
Sorry, pushed now

**Comment by TomasHofman** [comment]
Great, can see it now :). Downstream PR: https://github.com/jgroups-extras/jgroups-kubernetes/pull/124

**Pull request merged**
